blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/ViTeXFTW/ZeroSyntaxV2/blob/dev/SUPPORT.md
    about: Read where to ask support questions before opening an issue.
